<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adote_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get adote by id_adote
     */
    function get_adote($id_adote)
    {
        return $this->db->get_where('adote',array('id_adote'=>$id_adote))->row_array();
    }
        
    /*
     * Get all adote
     */
    function get_all_adote()
    {
        return $this->db->query("SELECT * FROM adote NATURAL JOIN catioro;")->result_array();
    }
        
    /*
     * function to add new adote
     */
    function add_adote($params)
    {
        $this->db->insert('adote',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update adote
     */
    function update_adote($id_adote,$params)
    {
        $this->db->where('id_adote',$id_adote);
        return $this->db->update('adote',$params);
    }
    
    /*
     * function to delete adote
     */
    function delete_adote($id_adote)
    {
        return $this->db->delete('adote',array('id_adote'=>$id_adote));
    }
}