<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ajudante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ajudante by id_ajud
     */
    function get_ajudante($id_ajud)
    {
        return $this->db->get_where('ajudante',array('id_ajud'=>$id_ajud))->row_array();
    }
    
    function count_ajud()
    {
        return $this->db->query("SELECT COUNT(1) AS 'count_ajud' FROM ajudante;")->row_array();
    }
        
    /*
     * Get all ajudante
     */
    function get_all_ajudante()
    {
        $this->db->order_by('id_ajud', 'desc');
        return $this->db->get('ajudante')->result_array();
    }
        
    /*
     * function to add new ajudante
     */
    function add_ajudante($params)
    {
        $this->db->insert('ajudante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ajudante
     */
    function update_ajudante($id_ajud,$params)
    {
        $this->db->where('id_ajud',$id_ajud);
        return $this->db->update('ajudante',$params);
    }
    
    /*
     * function to delete ajudante
     */
    function delete_ajudante($id_ajud)
    {
        return $this->db->delete('ajudante',array('id_ajud'=>$id_ajud));
    }
}