<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Catioro_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get catioro by id_cat
     */
    function get_catioro($id_cat)
    {
        return $this->db->get_where('catioro',array('id_cat'=>$id_cat))->row_array();
    }
    
    function count_catioro_adotado()
    {
        return $this->db->query("SELECT COUNT(1) AS 'dog_adot' FROM catioro WHERE status_cat = '1';")->row_array();
    }
    
    function count_catioro()
    {
        return $this->db->query("SELECT COUNT(1) AS 'dog_count' FROM catioro;")->row_array();
    }
    
    function count_catioro_hosp()
    {
        return $this->db->query("SELECT COUNT(1) AS 'dog_hosp' FROM catioro WHERE status_cat = '3' OR status_cat = '2';")->row_array();
    }
        
    /*
     * Get all catioro
     */
    function get_all_catioro()
    {
        $this->db->order_by('status_cat', 'ASC');
        return $this->db->get('catioro')->result_array();
    }
        
    /*
     * function to add new catioro
     */
    function add_catioro($params)
    {
        $this->db->insert('catioro',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update catioro
     */
    function update_catioro($id_cat,$params)
    {
        $this->db->where('id_cat',$id_cat);
        return $this->db->update('catioro',$params);
    }
    
    /*
     * function to delete catioro
     */
    function delete_catioro($id_cat)
    {
        return $this->db->delete('catioro',array('id_cat'=>$id_cat));
    }
}