<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Financeiro_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get financeiro by id_fin
     */
    function get_financeiro($id_fin)
    {
        return $this->db->get_where('financeiro',array('id_fin'=>$id_fin))->row_array();
    }
        
    /*
     * Get all financeiro
     */
    function get_all_financeiro()
    {
        $this->db->order_by('id_fin', 'desc');
        return $this->db->get('financeiro')->result_array();
    }
        
    /*
     * function to add new financeiro
     */
    function add_financeiro($params)
    {
        $this->db->insert('financeiro',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update financeiro
     */
    function update_financeiro($id_fin,$params)
    {
        $this->db->where('id_fin',$id_fin);
        return $this->db->update('financeiro',$params);
    }
    
    /*
     * function to delete financeiro
     */
    function delete_financeiro($id_fin)
    {
        return $this->db->delete('financeiro',array('id_fin'=>$id_fin));
    }
}