<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get login by id_login
     */
    function get_login($id_login)
    {
        return $this->db->get_where('login',array('id_login'=>$id_login))->row_array();
    }
    
     function get_user_login($user_login)
    {
        return $this->db->get_where('login',array('user_login'=>$user_login))->row_array();
    }
    
    function enter($user, $pass)
    {
        return $this->db->query("SELECT * FROM login WHERE user_login = '".$user."' AND senha_login = '".$pass."';")->row_array();
    }
        
    /*
     * Get all login
     */
    function get_all_login()
    {
        $this->db->order_by('id_login', 'desc');
        return $this->db->get('login')->result_array();
    }
        
    /*
     * function to add new login
     */
    function add_login($params)
    {
        $this->db->insert('login',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update login
     */
    function update_login($id_login,$params)
    {
        $this->db->where('id_login',$id_login);
        return $this->db->update('login',$params);
    }
    
    /*
     * function to delete login
     */
    function delete_login($id_login)
    {
        return $this->db->delete('login',array('id_login'=>$id_login));
    }
}