<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Parceiro_model extends CI_Model{
    /*
     * Get parceiro by id_parc
     */
    function get_parceiro($id_parc){
      
        return $this->db->get_where('parceiros',array('id_parc'=>$id_parc))->row_array();
    }
        
    /*
     * Get all parceiros
     */
    function get_all_parceiros(){
      
        $this->db->order_by('id_parc', 'desc');
        return $this->db->get('parceiros')->result_array();
    }
        
    /*
     * function to add new parceiro
     */
    function add_parceiro($params){
      
        $this->db->insert('parceiros',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update parceiro
     */
    function update_parceiro($id_parc,$params){
      
        $this->db->where('id_parc',$id_parc);
        return $this->db->update('parceiros',$params);
    }
    
    /*
     * function to delete parceiro
     */
    function delete_parceiro($id_parc){
      
        return $this->db->delete('parceiros',array('id_parc'=>$id_parc));
    }
}